### ISSUE TITLE
How do I run jar/jad?

### ISSUE THREAD

**Issue by vadosnaprimer** [kifferltd/open-mika#10]
I got the program to run on a debian vm, but if I extract the jar (I'm trying diamond rush) and tell it the class path, I get this:

```
./mika -cp . GloftDIRU
Init: unable to invoke null: java.lang.ClassNotFoundException: javax.microedition.midlet.MIDlet
java.lang.ClassNotFoundException: javax.microedition.midlet.MIDlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:165)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:284)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:304)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:304)
	at java.lang.Class.get_one_method(Native Method)
	at java.lang.Class.getMethod(Class.java:662)
	at wonka.vm.Init.main(Init.java:355)
Init: no 'main(String[])' method found. Game over.
```
Is there a proper way to run jar or jad? Does this game work for you? Maybe I'm doing this wrong?

**Comment by kiffer580** [comment]
Looks like the game you are trying to run us designed for MIDP environment, and Mika doesn't provide that profile; only CDC-FP or CDC-PP. If you got past javax.microedition.midlet.MIDlet then you would run up against javax.microedition.lcdui which we also do not have.

MIDP support was never one of Mika's design goals but I have to admit it would be cool. There seems to be a GPL's MIDP emulator project at http://kickjava.com/src/javax/microedition/, maybe try putting that stuff on your classpath and see what happens? Let me know if it works ...

**Comment by vadosnaprimer** [comment]
GPL MIDP emulator? I found one, from Java themselves, a couple years ago, called PhoneME. I cloned the entire repo right before it got shut down. I store it here: https://github.com/PhoneJ2ME
I might try classes from both, but since I'm actually only interested in CLDC emulation, it might be more efficient to just run those implementations instead?

Anyway, what apps does Mika aim to run?

**Comment by kiffer580** [comment]
Mika aims to run applications written to the JavaME CDC/FP 1.1 specification, see <http://www.oracle.com/technetwork/java/embedded/javame/overview-jsp-141092.html>. CDC is designed for devices which have just a bit more memory than CLDC was defined for, so a much larger subset of JavaSE is supported - BUT it doesn't have a couple of packages which were developed specifically for CLDC, namely midlet and lcdui.
When Mika was first developed our primary aim was to be able to support the "Foundation Execution Environment" of OSGi, see <https://www.osgi.org/developer/specifications/reference/#ReferenceEEs>. CLDC didn't cut it, so we made no effort to support CLDC. Now that I look at the kickjava stuff I'm tempted to have a go at running that on top of Mika, so that customers could use lcdui for example (or midlets, but midlets suck).
Mika is still being used in some embedded applications because it's quite small, it runs on architectures like mips and sh4, and of course there are no darn per-unit license fees to bother about. Almost all of these devices have no screen at all so they don't care whether we support lcgui or awt (we do support java.awt).
I'm tempted to snarf your PhoneJ2ME archive, but old habits die hard and I'm reluctant to come into contact with Sun's (or Oracle's) source code ...

**Comment by vadosnaprimer** [comment]
Oh, thanks for all the details! Maybe it should be mentioned in the readme? Lately J2ME gets some interest, and I'm sure it will raise over the years, when people approach seriously to emulating all the mobile games. So they will keep coming here trying to run wrong stuff and getting confused.

The C side of the code is indeed quote terrible, but the Java classes used for actual stuff may be helpful.

**Comment by Silent-Hunter** [comment]
Hey, did adding the PhoneME or kickjava stuff ever work?
